services:
  kafka-producer:
    build: .
    container_name: kafka-producer
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - spark-master
    env_file:
      - .env
    command: >
      sh -c "python3 SparkMovieProcessor.py && python3 UserActivitySimulator.py && python3 KafkaSparkConsumer.py"
    networks:
      - kafka_network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
    environment:
      - SPARK_MODE=master
    networks:
      - kafka_network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - kafka_network

  airflow:
    image: apache/airflow:latest
    container_name: airflow
    ports:
      - "8081:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - spark-master
    networks:
      - kafka_network

networks:
  kafka_network:
